'use client'

import { useMemo, useState } from 'react'
import useSWR from 'swr'
import { AlertCircle, Check, Database, FileJson, LayoutDashboard, Loader2, LogOut, Plus, Search, ShieldCheck, Sparkles, Trash2, Upload, Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { useUser } from '@/hooks/use-user'

const supabase = createClient()
type Anime = { slug: string; title: string; poster: string | null; hidden: boolean; featured: boolean; created_at: string }
type Episode = { id: string; anime_slug: string; season: number; episode: number; name: string; url: string; removed: boolean }
type ImportItem = { kind: 'anime' | 'episode'; title: string; slug: string; poster: string; anime_slug: string; season: number; episode: number; name: string; url: string }

function normalizeSlug(value: string) { return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 200) }
function detectItems(input: unknown): ImportItem[] {
  const found: ImportItem[] = []
  const visit = (value: unknown, parent?: Record<string, unknown>, parentTitle = '', parentSlug = '') => {
    if (Array.isArray(value)) return value.forEach((item) => visit(item, parent, parentTitle, parentSlug))
    if (!value || typeof value !== 'object') return
    const item = value as Record<string, unknown>
    const ownTitle = String(item.title ?? item.nome ?? item.name ?? item.anime ?? '')
    const title = ownTitle || parentTitle
    const ownSlug = String(item.slug ?? item.anime_slug ?? item.anime ?? '')
    const animeSlug = normalizeSlug(ownSlug || parentSlug || title)
    const url = typeof item.url === 'string' ? item.url : typeof item.video_url === 'string' ? item.video_url : ''
    const season = Number(item.season ?? item.temporada ?? parent?.season ?? 1) || 1
    const episode = Number(item.episode ?? item.episodio ?? item.ep ?? 0) || 0
    const poster = String(item.poster ?? item.image ?? item.cover ?? parent?.poster ?? '')
    if (url && episode > 0) found.push({ kind: 'episode', title: title || `Episódio ${episode}`, slug: animeSlug, poster, anime_slug: animeSlug, season, episode, name: String(item.nome ?? item.name ?? title), url })
    else if (!url && title && (item.poster || item.image || item.cover || item.slug || item.temporadas || item.seasons)) found.push({ kind: 'anime', title, slug: normalizeSlug(String(item.slug ?? title)), poster, anime_slug: '', season: 1, episode: 0, name: '', url: '' })
    Object.entries(item).forEach(([key, child]) => {
      if (key === 'url' || key === 'video_url' || key === 'poster' || key === 'image' || key === 'cover') return
      const keyIsAnime = typeof child === 'object' && child !== null && !Array.isArray(child) && !ownTitle && !item.slug
      visit(child, item, keyIsAnime ? key : title, keyIsAnime ? normalizeSlug(key) : animeSlug)
    })
  }
  if (input && typeof input === 'object' && !Array.isArray(input)) {
    Object.entries(input as Record<string, unknown>).forEach(([key, value]) => visit(value, undefined, key, normalizeSlug(key)))
  } else visit(input)
  return Array.from(new Map(found.map((item) => [`${item.kind}:${item.kind === 'anime' ? item.slug : `${item.anime_slug}:${item.season}:${item.episode}`}`, item])).values())
}

async function fetchAdminData() {
  const [{ data: animes }, { data: episodes }, { data: logs }] = await Promise.all([
    supabase.from('catalog_animes').select('*').order('created_at', { ascending: false }),
    supabase.from('catalog_episodes').select('*').order('created_at', { ascending: false }).limit(100),
    supabase.from('admin_log').select('id, action, detail, created_at').order('created_at', { ascending: false }).limit(20),
  ])
  return { animes: (animes ?? []) as Anime[], episodes: (episodes ?? []) as Episode[], logs: logs ?? [] }
}

export function AdminDashboard() {
  const { user, isLoading: userLoading, refreshUser } = useUser()
  const { data, mutate } = useSWR(user?.isAdmin ? 'admin-catalog' : null, fetchAdminData)
  const [tab, setTab] = useState<'overview' | 'import' | 'catalog' | 'activity'>('overview')
  const [json, setJson] = useState('')
  const [preview, setPreview] = useState<ImportItem[]>([])
  const [notice, setNotice] = useState<{ type: 'ok' | 'error'; text: string } | null>(null)
  const [busy, setBusy] = useState(false)
  const [query, setQuery] = useState('')

  const filtered = useMemo(() => (data?.animes ?? []).filter((item) => item.title.toLowerCase().includes(query.toLowerCase())), [data?.animes, query])
  const run = async (action: () => Promise<void>) => { setBusy(true); setNotice(null); try { await action(); await mutate(); setNotice({ type: 'ok', text: 'Alterações guardadas com sucesso.' }) } catch (error) { setNotice({ type: 'error', text: error instanceof Error ? error.message : 'Não foi possível concluir a operação.' }) } finally { setBusy(false) } }
  const claimAdmin = async () => { setBusy(true); const { data: claimed, error } = await supabase.rpc('claim_first_admin'); if (error || !claimed) setNotice({ type: 'error', text: 'Já existe um administrador ou a conta ainda não está pronta.' }); else { setNotice({ type: 'ok', text: 'A tua conta é agora a primeira administradora.' }); await refreshUser() }; setBusy(false) }
  const importData = async () => { const items = detectItems(JSON.parse(json)); if (!items.length) throw new Error('Não encontrei animes ou episódios reconhecíveis neste JSON.'); const animeItems = items.filter((item) => item.kind === 'anime'); const episodeItems = items.filter((item) => item.kind === 'episode'); if (animeItems.length) { const { error } = await supabase.from('catalog_animes').upsert(animeItems.map((item) => ({ slug: item.slug, title: item.title, poster: item.poster || null })), { onConflict: 'slug' }); if (error) throw error } if (episodeItems.length) { const slugs = Array.from(new Set(episodeItems.map((item) => item.anime_slug))); const { error: animeError } = await supabase.from('catalog_animes').upsert(slugs.map((slug) => ({ slug, title: slug.replaceAll('-', ' '), poster: null })), { onConflict: 'slug' }); if (animeError) throw animeError; const { error } = await supabase.from('catalog_episodes').upsert(episodeItems.filter((item) => item.episode > 0).map((item) => ({ anime_slug: item.anime_slug, season: item.season, episode: item.episode, name: item.name, url: item.url })), { onConflict: 'anime_slug,season,episode' }); if (error) throw error } await supabase.from('admin_log').insert({ admin_id: user?.id, action: 'import_json', detail: `${animeItems.length} animes e ${episodeItems.length} episódios` }); setPreview([]); setJson(''); }
  if (userLoading) return <div className="flex min-h-[50vh] items-center justify-center text-muted-foreground"><Loader2 className="mr-2 size-5 animate-spin" />A verificar a tua conta...</div>
  if (!user) return <Gate icon={<ShieldCheck />} title="Área reservada" text="Inicia sessão para gerir o MB Animes." action="Entrar" href="/auth/login" />
  if (!user.isAdmin) return <Gate icon={<ShieldCheck />} title="Acesso de administrador" text="Esta área é protegida. Se és o primeiro responsável pelo site, podes assumir a administração uma única vez." action={busy ? 'A preparar...' : 'Reivindicar primeiro acesso'} onClick={claimAdmin} />

  const nav = [{ id: 'overview', label: 'Visão geral', icon: LayoutDashboard }, { id: 'import', label: 'Importar JSON', icon: FileJson }, { id: 'catalog', label: 'Catálogo', icon: Database }, { id: 'activity', label: 'Atividade', icon: Users }] as const
  return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-primary"><Sparkles className="size-4" />Centro de comando</p><h1 className="font-serif text-4xl font-bold text-foreground">Painel MB Animes</h1><p className="mt-2 text-muted-foreground">Gere o catálogo sem editar ficheiros manualmente.</p></div><button onClick={() => supabase.auth.signOut()} className="flex items-center gap-2 self-start rounded-lg border border-border px-4 py-2 text-sm font-semibold text-muted-foreground transition hover:border-primary hover:text-foreground"><LogOut className="size-4" />Sair</button></div><div className="grid gap-6 lg:grid-cols-[220px_1fr]"><aside className="rounded-xl border border-border bg-card p-2"><nav className="flex gap-1 overflow-x-auto lg:flex-col">{nav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-semibold transition ${tab === id ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon className="size-4" />{label}</button>)}</nav></aside><main className="min-w-0">{notice && <div className={`mb-5 flex items-center gap-2 rounded-lg border px-4 py-3 text-sm ${notice.type === 'ok' ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-600' : 'border-destructive/30 bg-destructive/10 text-destructive'}`}>{notice.type === 'ok' ? <Check className="size-4" /> : <AlertCircle className="size-4" />}{notice.text}</div>}{tab === 'overview' && <Overview data={data} setTab={setTab} />} {tab === 'import' && <ImportPanel json={json} setJson={setJson} preview={preview} setPreview={setPreview} onAnalyze={() => { try { const items = detectItems(JSON.parse(json)); if (!items.length) throw new Error('Não encontrei conteúdo reconhecível. Confirma se o JSON está completo e válido.'); setPreview(items); setNotice({ type: 'ok', text: `Reconhecidos ${items.filter((item) => item.kind === 'anime').length} animes e ${items.filter((item) => item.kind === 'episode').length} episódios.` }) } catch { setPreview([]); setNotice({ type: 'error', text: 'O JSON está incompleto ou inválido. Cola o objeto completo, sem a vírgula final.' }) } }} importData={importData} busy={busy} />} {tab === 'catalog' && <CatalogPanel animes={filtered} episodes={data?.episodes ?? []} query={query} setQuery={setQuery} run={run} />} {tab === 'activity' && <Activity logs={data?.logs ?? []} />}</main></div></div>
}

function Gate({ icon, title, text, action, href, onClick }: { icon: React.ReactNode; title: string; text: string; action: string; href?: string; onClick?: () => void }) { return <div className="mx-auto flex min-h-[55vh] max-w-xl flex-col items-center justify-center px-6 text-center"><div className="mb-5 rounded-2xl border border-primary/30 bg-primary/10 p-4 text-primary">{icon}</div><h1 className="font-serif text-3xl font-bold">{title}</h1><p className="mt-3 max-w-md text-muted-foreground">{text}</p>{href ? <a href={href} className="mt-6 rounded-lg bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">{action}</a> : <button disabled={action.includes('...')} onClick={onClick} className="mt-6 rounded-lg bg-primary px-5 py-3 text-sm font-bold text-primary-foreground disabled:opacity-50">{action}</button>}</div> }
function Overview({ data, setTab }: { data?: Awaited<ReturnType<typeof fetchAdminData>>; setTab: (tab: 'overview' | 'import' | 'catalog' | 'activity') => void }) { return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-3">{[['Animes', data?.animes.length ?? 0], ['Episódios', data?.episodes.length ?? 0], ['Destaques', data?.animes.filter((a) => a.featured).length ?? 0]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 font-mono text-3xl font-bold text-foreground">{value}</p></div>)}</div><div className="rounded-xl border border-border bg-card p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="font-serif text-2xl font-bold">Adicionar conteúdo</h2><p className="mt-1 text-sm text-muted-foreground">Cola o JSON e deixa o painel reconhecer o tipo de conteúdo.</p></div><button onClick={() => setTab('import')} className="hidden items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-bold text-primary-foreground sm:flex"><Plus className="size-4" />Importar</button></div></div></div> }
function ImportPanel({ json, setJson, preview, onAnalyze, importData, busy }: { json: string; setJson: (v: string) => void; preview: ImportItem[]; setPreview: (v: ImportItem[]) => void; onAnalyze: () => void; importData: () => Promise<void>; busy: boolean }) { return <div className="space-y-5"><SimpleAddForm /><div><h2 className="font-serif text-3xl font-bold">Importação inteligente</h2><p className="mt-1 text-sm text-muted-foreground">Aceita JSON de anime, temporada ou episódios. O sistema deteta a estrutura e evita duplicados.</p></div><textarea value={json} onChange={(e) => setJson(e.target.value)} placeholder={'Cola aqui o teu JSON...'} className="min-h-72 w-full rounded-xl border border-border bg-card p-4 font-mono text-xs leading-6 outline-none focus:border-primary" /><div className="flex flex-wrap gap-3"><button type="button" onClick={onAnalyze} className="flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-bold hover:border-primary"><Search className="size-4" />Analisar JSON</button><button type="button" disabled={busy || !preview.length} onClick={() => void importData()} className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-bold text-primary-foreground disabled:opacity-50"><Upload className="size-4" />{busy ? 'A importar...' : 'Importar conteúdo'}</button></div>{preview.length > 0 && <div className="rounded-xl border border-border bg-card p-5"><p className="mb-3 text-sm font-bold">Reconhecido: {preview.filter((i) => i.kind === 'anime').length} animes e {preview.filter((i) => i.kind === 'episode').length} episódios</p><div className="max-h-64 space-y-2 overflow-auto">{preview.slice(0, 40).map((item, index) => <div key={`${item.kind}-${index}`} className="flex items-center justify-between border-b border-border py-2 text-sm"><span className="truncate">{item.title || item.anime_slug}</span><span className="ml-3 shrink-0 rounded bg-muted px-2 py-1 text-xs text-muted-foreground">{item.kind === 'anime' ? 'Anime' : `T${item.season} EP${item.episode}`}</span></div>)}</div></div>}</div> }
function CatalogPanel({ animes, episodes, query, setQuery, run }: { animes: Anime[]; episodes: Episode[]; query: string; setQuery: (v: string) => void; run: (action: () => Promise<void>) => Promise<void> }) { return <div className="space-y-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="font-serif text-3xl font-bold">Catálogo</h2><p className="mt-1 text-sm text-muted-foreground">Oculta, destaca ou remove títulos e acompanha episódios.</p></div><label className="flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2"><Search className="size-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Filtrar animes" className="w-40 bg-transparent text-sm outline-none" /></label></div><div className="overflow-hidden rounded-xl border border-border bg-card"><div className="divide-y divide-border">{animes.map((anime) => <div key={anime.slug} className="flex flex-wrap items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="truncate font-semibold">{anime.title}</p><p className="font-mono text-xs text-muted-foreground">{anime.slug} · {episodes.filter((ep) => ep.anime_slug === anime.slug).length} episódios</p></div><div className="flex items-center gap-2"><button onClick={() => void run(async () => { const { error } = await supabase.from('catalog_animes').update({ featured: !anime.featured }).eq('slug', anime.slug); if (error) throw error })} className={`rounded-md px-3 py-1.5 text-xs font-bold ${anime.featured ? 'bg-primary text-primary-foreground' : 'border border-border text-muted-foreground'}`}>{anime.featured ? 'Destaque' : 'Destacar'}</button><button onClick={() => void run(async () => { const { error } = await supabase.from('catalog_animes').update({ hidden: !anime.hidden }).eq('slug', anime.slug); if (error) throw error })} className="rounded-md border border-border px-3 py-1.5 text-xs font-bold text-muted-foreground">{anime.hidden ? 'Mostrar' : 'Ocultar'}</button><button aria-label={`Eliminar ${anime.title}`} onClick={() => { if (window.confirm(`Eliminar ${anime.title} e os seus episódios?`)) void run(async () => { const { error } = await supabase.from('catalog_animes').delete().eq('slug', anime.slug); if (error) throw error }) }} className="rounded-md p-2 text-destructive hover:bg-destructive/10"><Trash2 className="size-4" /></button></div></div>)}{!animes.length && <div className="p-8 text-center text-sm text-muted-foreground">Nenhum anime encontrado.</div>}</div></div></div> }
function SimpleAddForm() {
  const [mode, setMode] = useState<'anime' | 'episode'>('episode')
  const [animeSlug, setAnimeSlug] = useState('')
  const [title, setTitle] = useState('')
  const [poster, setPoster] = useState('')
  const [season, setSeason] = useState('1')
  const [episode, setEpisode] = useState('1')
  const [url, setUrl] = useState('')
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const save = async () => {
    setSaving(true)
    setMessage('')
    try {
      const slug = mode === 'anime' ? normalizeSlug(title) : normalizeSlug(animeSlug)
      if (!slug || !title.trim() && mode === 'anime') throw new Error('Preenche o título do anime.')
      if (mode === 'episode' && (!slug || !url.trim())) throw new Error('Preenche o anime e o link do episódio.')
      if (mode === 'anime') {
        const { error } = await supabase.from('catalog_animes').upsert({ slug, title: title.trim(), poster: poster.trim() || null }, { onConflict: 'slug' })
        if (error) throw error
      } else {
        const { error: animeError } = await supabase.from('catalog_animes').upsert({ slug, title: title.trim() || slug.replaceAll('-', ' '), poster: poster.trim() || null }, { onConflict: 'slug' })
        if (animeError) throw animeError
        const { error } = await supabase.from('catalog_episodes').upsert({ anime_slug: slug, season: Number(season), episode: Number(episode), name: title.trim() || `Episódio ${episode}`, url: url.trim() }, { onConflict: 'anime_slug,season,episode' })
        if (error) throw error
      }
      setMessage(mode === 'anime' ? 'Anime guardado.' : 'Episódio guardado.')
      if (mode === 'episode') setUrl('')
      window.dispatchEvent(new Event('admin-catalog-updated'))
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível guardar.') } finally { setSaving(false) }
  }
  return <section className="rounded-xl border border-primary/25 bg-primary/5 p-5"><div className="mb-4"><h3 className="font-serif text-xl font-bold">Adicionar sem JSON</h3><p className="text-sm text-muted-foreground">Para um anime novo, uma temporada ou apenas o próximo episódio.</p></div><div className="mb-4 flex gap-2"><button type="button" onClick={() => setMode('episode')} className={`rounded-lg px-3 py-2 text-sm font-bold ${mode === 'episode' ? 'bg-primary text-primary-foreground' : 'border border-border text-muted-foreground'}`}>Episódio / temporada</button><button type="button" onClick={() => setMode('anime')} className={`rounded-lg px-3 py-2 text-sm font-bold ${mode === 'anime' ? 'bg-primary text-primary-foreground' : 'border border-border text-muted-foreground'}`}>Anime novo</button></div><div className="grid gap-3 sm:grid-cols-2"><input value={mode === 'anime' ? title : animeSlug} onChange={(e) => mode === 'anime' ? setTitle(e.target.value) : setAnimeSlug(e.target.value)} placeholder={mode === 'anime' ? 'Nome do anime' : 'Slug do anime existente'} className="rounded-lg border border-border bg-card px-3 py-2 text-sm outline-none focus:border-primary" />{mode === 'episode' && <input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Nome do episódio (opcional)" className="rounded-lg border border-border bg-card px-3 py-2 text-sm outline-none focus:border-primary" />}{mode === 'anime' && <input value={poster} onChange={(e) => setPoster(e.target.value)} placeholder="URL do poster (opcional)" className="rounded-lg border border-border bg-card px-3 py-2 text-sm outline-none focus:border-primary" />}{mode === 'episode' && <><input value={season} onChange={(e) => setSeason(e.target.value)} inputMode="numeric" placeholder="Temporada" className="rounded-lg border border-border bg-card px-3 py-2 text-sm outline-none focus:border-primary" /><input value={episode} onChange={(e) => setEpisode(e.target.value)} inputMode="numeric" placeholder="Episódio" className="rounded-lg border border-border bg-card px-3 py-2 text-sm outline-none focus:border-primary" /><input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="URL direta do vídeo" className="sm:col-span-2 rounded-lg border border-border bg-card px-3 py-2 text-sm outline-none focus:border-primary" /></>}</div><div className="mt-4 flex items-center gap-3"><button type="button" onClick={() => void save()} disabled={saving} className="rounded-lg bg-primary px-4 py-2 text-sm font-bold text-primary-foreground disabled:opacity-50">{saving ? 'A guardar...' : 'Guardar no catálogo'}</button>{message && <span className="text-sm text-muted-foreground">{message}</span>}</div></section> }

function Activity({ logs }: { logs: { id: string; action: string; detail: string; created_at: string }[] }) { return <div><h2 className="font-serif text-3xl font-bold">Atividade</h2><p className="mt-1 text-sm text-muted-foreground">Histórico das alterações feitas no catálogo.</p><div className="mt-5 divide-y divide-border rounded-xl border border-border bg-card">{logs.map((log) => <div key={log.id} className="flex items-center justify-between gap-4 p-4 text-sm"><div><p className="font-semibold">{log.action}</p><p className="text-muted-foreground">{log.detail}</p></div><time className="shrink-0 text-xs text-muted-foreground">{new Date(log.created_at).toLocaleDateString('pt-PT')}</time></div>)}{!logs.length && <p className="p-8 text-center text-sm text-muted-foreground">Ainda não existem ações registadas.</p>}</div></div> }
